### ISSUE TITLE
Question about calculating ACC

### ISSUE THREAD

**Issue by labiao** [DeifiliaTo/PanguWeather#4]
I have observed that the ACC values are occasionally negative. The reason is that the variable ‘numerator’ is negative values in some case. Is it normal for ACC to have negative values? From my understanding, ACC should ideally range from 0 to 1, where 1 indicates perfect correlation, and 0 indicates no correlation. Negative values suggest a negative correlation, which I'm not sure should happen in this context.
![db979521-eccf-4177-b4f1-c3d3e1ce0a5a](https://github.com/user-attachments/assets/3a4b309f-84a6-4e07-bd7d-3e8d39fadcee)

**Comment by DeifiliaTo** [comment]
This is because at the beginning, the initialized fields are random. So we expect ACC values to be in the neighborhood of 0 (either slightly positive or slightly negative). It's possible for the results to be slightly negatively correlated, but they  improve to be > 0 as the model is improved through training.
